version: "2"

services:
  frontend:
    build: .
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: ["/bin/sh", "-c", "yarn && yarn dev"]
    environment:
      HOST: 0.0.0.0
networks:
  default:
    external:
      name: coin_locker_network
